version: '3.9'

services:
  tripservice-db:
    image: postgres:16
    container_name: tripservice-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tripdb
    ports:
      - "5432:5432"
    volumes:
      - tripdata:/var/lib/postgresql/data
    networks:
      - tripnetwork

  tripservice-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tripservice-app
    ports:
      - "5000:8080"
    depends_on:
      - tripservice-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=tripservice-db;Database=tripdb;Username=postgres;Password=postgres
    networks:
      - tripnetwork

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - tripnetwork

volumes:
  tripdata:

networks:
  tripnetwork:
